### ISSUE TITLE
Split google_fonts.dart into multiple files

### ISSUE THREAD

**Issue by marchellodev** [material-foundation/flutter-packages#137]
Right now it is impossible to navigate through `google_fonts.dart`.
Since it weights about 3mb, Intellij's code navigation feature is not available. Therefore, it is impossible to jump to the source code from the IDE.
It is impossible to view this file on GitHub too: `(Sorry about that, but we can’t show files that are this big right now.)`

Is it possible to split this file into multiple pieces?

![image](https://user-images.githubusercontent.com/61112084/101260228-0d409f80-3737-11eb-990c-d65a08fdf64d.png)

**Comment by johnsonmh** [comment]
This is a good idea, I've been frustrated by that before too, never thought to split out the generated code. 

I feel like we could split it out by number, letter, or groups of letters, depending on how many files we want.

For example
 1. `src/google_fonts_1.dart`
 1. `src/google_fonts_a.dart`
 1. `src/google_fonts_a_f.dart`

Then `google_fonts.dart` would just be written to export the other generated files (that way the library still works the same with `import 'package:google_fonts/google_fonts.dart'`

@clocksmith WDYT?

**Comment by johnsonmh** [comment]
Now that I think about it, I'm not sure how that would work with the `GoogleFonts.foo` API, because if the methods are in separate files, they can't all be inside the single `GoogleFonts` class. 

Curious to hear thoughts/ideas for addressing this.
