### ISSUE TITLE
Unable to load issue with Rubik Fonts

### ISSUE THREAD

**Issue by ankitmiyan30** [material-foundation/flutter-packages#280]
google_fonts was unable to load font Rubik-Regular because the following exception occurred:
Exception: Failed to load font with url: https://fonts.gstatic.com/s/a/c07d3baa06bab48792c91759b27518f6ce25935caf229e36fd9771e6b8301cde.ttf

Flutter Doctor

Flutter (Channel stable, 3.3.8, on macOS 12.5.1 21G83 darwin-arm, locale
    en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.73.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

**Comment by esouthren** [comment]
Hi @ankitmiyan30, thank you for filing an issue. 

I'm unable to reproduce this - I can use `GoogleFonts.rubik()` successfully on Chrome and MacOS.

Can you give me some more information, such as:
- The platform you are running your Flutter app on 
- Whether this only happens with the `rubik` font, or all fonts

**Comment by shockbytes** [comment]
@ankitmiyan30 I think you might miss the following snippet for your Macos application: https://pub.dev/packages/google_fonts#http-fetching

**Comment by adiiisanjayaa** [comment]
any update?

**Comment by ankitmiyan30** [comment]
The issue was resolved by upgrading Flutter to 3.10.* and google_fonts to version: 4.0.5.
