### ISSUE TITLE
Library Issues and Feedback

### ISSUE THREAD

**Issue by salihgueler** [material-foundation/flutter-packages#307]
Hello team,

Normally I think this would have been better as a "Discussion" on GitHub but since it is not enabled, I would like to share some feedback and bugs that I have seen with you. I created a seperate issue for each bug but you can find the feedbacks below. I can provide code snuppet for each scenario. 

- [feedback][adaptive_components] : For the Column logic over the `columnSpan` property only documentation I can find is the [official doc](https://material.io/design/layout/responsive-layout-grid.html#columns-gutters-and-margins), but it either does not explain the logic properly or the library is inconsistent. e.g. When I have different columnSpans, I would expect the see the items as a wrap (aka one below after another) in the worst case scenario. But in a scenario that I have 4 items, sometimes it shows all, sometimes only two sometimes not at all. With a better explanation of the columnSpan I think we can have a better definition of the behavior.
- [feedback][adaptive_navigation] : Why bottom navigation overflow can be assigned but rail navigation overflow number is limited to 7? Is there a logic behind it?
- [bug][adaptive_navigation]: https://github.com/material-components/material-components-flutter-adaptive/issues/61
- [bug][flutter_adaptive_scaffold] : https://github.com/material-components/material-components-flutter-adaptive/issues/63
- [feedback][adaptive_components] : When we have an Adaptive Column on the same level with. Adaptive Containers, if the Adaptive Column is the last item or if the container does not match the max screen size, the items of the column is not shown. I wonder if it is a bug or am I missing a pattern, I can provide code snippet if required.

**Comment by guidezpl** [comment]
Thank you for the thoughtful feedback, I don't have cycles to get to this soon, but hopefully later.

**Comment by guidezpl** [comment]
Closing this issue due to discontinuation of the adaptive packages.
