### ISSUE TITLE
[flutter_adaptive_scaffold] When useDrawer is false, the bottom navigation bar does not work

### ISSUE THREAD

**Issue by salihgueler** [material-foundation/flutter-packages#308]
Steps to reproduce:

- Add an adaptive Scaffold
- add useDrawer: false to the scaffold
- Make the screen small enough to use bottom navigation bar
- Click on items
Current:
The callback does not work
Expected:
Callback should work

**Comment by guidezpl** [comment]
Hi just realized this issue would be best suited for github.com/flutter/flutter since the package lives in flutter/packages, so I'll close this
