### ISSUE TITLE
[adaptive_navigation] When the bottom navigation overflow is bigger than rail overflow app crashes

### ISSUE THREAD

**Issue by salihgueler** [material-foundation/flutter-packages#309]
Steps to reproduce
- Add 10 items to the navigation
- Add selected item behavior
- Change bottom navigation overflow to 10
- Select on the Element 8,9 or 10
- Change the UI to have navigation rail.
Current: 
App crashes
Expected:
App shows the elements and the correct item is selected.

**Comment by deepak-kumar-swain** [comment]
Any solution ?

**Comment by guidezpl** [comment]
Closing this issue due to discontinuation of the adaptive packages.
