### ISSUE TITLE
Tablet landscape cannot be differentiated

### ISSUE THREAD

**Issue by zeroDivider** [material-foundation/flutter-packages#310]
My team decided we will be using **adaptive_breakpoints** for handling responsiveness and it is good so far, we achieved almost everything we needed :) but there is one small thing that we cannot manage: we would like to have different UI for tablet landscape, but we never get there since we are always notified it is bigger and then we are displayed with same UI we use on web browsers on bigger screens. My guess is that it is okay for some big tablets, but not sure that there is any tablet that would display tablet landscape (at least we do not own it).
I am aware we can add a check if the device is tablet, but it does not sound like clean responsiveness practice.

Any advice on this situation?

**Comment by guidezpl** [comment]
That's a good question. I'm not sure if this helps, but we encode different breakpoints for portrait and landscape, e.g. https://pub.dev/documentation/adaptive_breakpoints/latest/adaptive_breakpoints/AdaptiveWindowType/large-constant.html
