### ISSUE TITLE
adaptive navigation not written to be performatn

### ISSUE THREAD

**Issue by fredgrott** [material-foundation/flutter-packages#314]
With the four functions returning widgets its not perormant as any time it updates it is force to update whole thing including widgets returned via functions rather then just the widgets that need updated.

Even though it might take a few hours to defange it via performance CPU cycles, it seems it be a worth while thing to do or complete.

I will do it internally as it makes some nice dev tech article to write. Not sure however when I get back to it to put in a code contribution to change it just yet.

**Comment by guidezpl** [comment]
Closing this issue due to discontinuation of the adaptive packages.
