### ISSUE TITLE
Adaptive column example has incomplete row

### ISSUE THREAD

**Issue by pennzht** [material-foundation/flutter-packages#319]
## How to reproduce this bug
1. Run the latest `develop` in Chrome.
2. Adjust the window's width.
3. Observe that sometimes a row is incomplete, while it should be.

## Possible causes
* Because of floating point rounding, a row's children might have a total width that is greater than the screen's width.

<img width="1059" alt="adaptive-columns-example-width" src="https://user-images.githubusercontent.com/23219899/94472914-bf09a000-01cb-11eb-998d-09063d160e53.png">

**Comment by guidezpl** [comment]
Closing this issue due to discontinuation of the adaptive packages.
