### ISSUE TITLE
[Adaptive Navigation] Menu icon is not center aligned with navigation rail items

### ISSUE THREAD

**Issue by clocksmith** [material-foundation/flutter-packages#320]
Currently:
![Screen Shot 2020-08-11 at 1 36 29 PM](https://user-images.githubusercontent.com/591699/89929902-e682ba00-dbd7-11ea-8265-94849522af0c.png)

Should be more like:
![Screen Shot 2020-08-11 at 1 37 17 PM](https://user-images.githubusercontent.com/591699/89929938-ee425e80-dbd7-11ea-9d25-8e5623ce0cc5.png)

**Comment by guidezpl** [comment]
Closing this issue due to discontinuation of the adaptive packages.
