### ISSUE TITLE
Prevent app from reloading after android dynamic color changes

### ISSUE THREAD

**Issue by tmaihoff** [material-foundation/flutter-packages#335]
Can I prevent my flutter app from reloading after I the android dynamic colors change?

I'd like to keep the app state and only have the colors change. Like in native android apps like Gmail, Calendar, etc. 

How to reproduce:
1. Open the flutter app with `DynamicColorBuilder`

2. Minimize the app without terminating it, long press the home screen and change the dynamic color scheme (on Pixel phone)

3. Go back to the flutter app and see it reloading.

**Comment by Azzy987** [comment]
> tmaihoff

Did you able to solve the issue?

**Comment by tmaihoff** [comment]
No, unfortunately not
