### ISSUE TITLE
Dynamically select the font

### ISSUE THREAD

**Issue by egorges** [material-foundation/flutter-packages#34]
Hi, this is for the **wishlist** - not sure if should file it elsewhere.

I´d like to select the font dynamically. 

Besides:
```
Text(
  'This is Google Fonts',
  style: GoogleFonts.lato(),
),
```

I´d like to have something similar to:
```
Text(
  'This is Google Fonts',
  style: GoogleFonts.setFont('Lato'),
),
```

thanks.

**Comment by johnsonmh** [comment]
We're curious to hear more about your use case. We could imagine a couple of ways to expose this type of feature, and how we do it would depend on your use case.

**Comment by egorges** [comment]
I'd like, for example, to let the user choose among 5 fonts and format it accordingly.
Maybe someone else would let the user select any font.

**Comment by johnsonmh** [comment]
OK, thanks for the follow up, we will think about how we might add this to the library.

Best advice I can give for now is to do something like a switch statement as a work around:

```dart
TextStyle googleFontFromName(String name) {
    switch(name.toLowerCase()) {
    case 'lato':
      return GoogleFonts.lato();
      break;
    case 'roboto':
      return GoogleFonts.roboto();
      break;
    default:
      return GoogleFonts.roboto();
      break;
  }
}
```

But this wouldn't scale if you want more than 5 fonts which, as you mentioned, users may want.

Thanks for the suggestion!

**Comment by egorges** [comment]
I also think dynamically may have the benefit of use new fonts, without a new App version, with something similar to:
GoogleFonts.getList();

**Comment by searchy2** [comment]
I have a similar use case. For a Flutter text editor, I would like to give the user the ability to select any font from a list.

**Comment by willlarche** [comment]
These ideas are good candidates for community contribution! Consider adding a pull request. We will not get to it very soon.

**Comment by searchy2** [comment]
Thanks for the status update. 

Can you point to the definitive list of available fonts? I'm looking at the font file generator but I don't see where the font list is pulled from. 

https://github.com/material-foundation/google-fonts-flutter/tree/master/generator

**Comment by searchy2** [comment]
Actually, the PR for this feature wouldn't required the source now that I think about it but it would be good info to know.

**Comment by clocksmith** [comment]
The fonts come from a proto that we fetch when we generator the library: https://github.com/material-foundation/google-fonts-flutter/blob/master/generator/generator.dart#L119

But yes you are right, you don't need access to that, because you can use this function to pass the font family directly: https://github.com/material-foundation/google-fonts-flutter/blob/master/lib/src/google_fonts_base.dart#L36

**Comment by johnsonmh** [comment]
Thanks to @krista-koivisto, this is now available with `GoogleFonts.getFont('Lato')`!
