### ISSUE TITLE
google fonts not supporting arabic number digits.

### ISSUE THREAD

**Issue by MahmoudMoGamal** [material-foundation/flutter-packages#369]
### Package

google_fonts

### Existing issue?

- [X] I checked the [existing issues](https://github.com/material-foundation/flutter-packages/issues)

## Expected vs actual result:
 I put number in a text expected to be in arabic format with tajawal font but it's in english form.

## Steps to reproduce:
1. add google fonts.
2. put tajawal as app font family.

**Comment by guidezpl** [comment]
There are not enough steps to reproduce this bug, can you please provide more details?
