### ISSUE TITLE
Font size on TestFlight app is VERY different from simulator / release mode. 

### ISSUE THREAD

**Issue by codingiswhyicry** [material-foundation/flutter-packages#370]
### Package

google_fonts

### Existing issue?

- [X] I checked the [existing issues](https://github.com/material-foundation/flutter-packages/issues)

### What happened?

Getting ready for a beta of an app, and I found out when I downloaded it from TestFlight that the actual font sizes appear to be quite different, to the point where it does break layouts and cause problems, even though the simulator / my actual device showed no deviation with the sizes. 

No accessibility settings for larger text are on my device, nor on the simulator. The simulator images are from an iPhone 12 mini, and I ran the codebase on my actual personal 12 mini, and saw no issues. 

Once I packaged the codebase and sent it through TestFlight, the font sizes changed pretty clearly when you look at the image side by side. I found one instance of this in the Apple Developer forums, but nothing too definitive about it. 

## Expected vs actual result:

Fonts to match size that rendered using the same iPhone size on Simulator, and even on device using release mode. 

## Steps to reproduce:
1. Package your app using google_fonts
2. Upload to App Store Connect and TestFlight 
3. Download the app using TestFlight 4. 

iPhone 12 mini simulator: 
![Simulator Screen Shot - iPhone 12 mini - 2023-03-14 at 13 02 06](https://user-images.githubusercontent.com/10201992/225125785-1c6168f6-a707-4357-8afc-fdb5d9874819.png)

My physical 12 mini, same codebase through TestFlight:
![FrNK0M7aYAAXEoX](https://user-images.githubusercontent.com/10201992/225125838-bedcceda-5d82-4242-8698-9c6cb4fda480.jpeg)

**Comment by codingiswhyicry** [comment]
A better side by side so you can see the differences more clearly. The size of the UI elements are more or less the same, but the font seems to be 3-4+ points in size difference. Not adjusting for different font sizes withstanding (something that's on my to-do list), the fact the same fonts from the same codebase on the same phone screen size looks so different is a bit weird to me. 

<img width="1440" alt="Screen Shot 2023-03-14 at 1 22 21 PM" src="https://user-images.githubusercontent.com/10201992/225127446-895a9160-b6fa-47dc-b4be-cf2bdc436268.png">

**Comment by guidezpl** [comment]
Can you please compare locally, debug and release modes? Could you also provide more context / code to reproduce (are you using local fonts or loading them, how are you defining the text styles, etc.)

**Comment by justsaagar** [comment]
I also face same issue. i Simply use the font in fontfamily like,

`GoogleFonts.instrumentSans().fontFamily`

And while i debug the app it's showing as light weightage even with `FontWeight.bold` but when I build with release version. It's having bold weightage in fonts. Which is why quite difficult to do code with this font family.

Every time i am not going to check with release mode which cost me too much time. Can you give me any solution?
