### ISSUE TITLE
google_fonts was unable to load font Belgrano-Regular because the following exception occurred:

### ISSUE THREAD

**Issue by ambika0710** [material-foundation/flutter-packages#385]
### Package

All packages

### Existing issue?

- [X] I checked the [existing issues](https://github.com/material-foundation/flutter-packages/issues)

## Steps to reproduce:
1.
1.Failed to load font with url: https://fonts.gstatic.com/s/a/041815a440e3d2b468ffa830185903956b5925796cfa68c5b61fa3c3b3f0f2cb.ttf
I/flutter (18496): 
1.

### Relevant log output

```shell
Failed to load font with url: https://fonts.gstatic.com/s/a/041815a440e3d2b468ffa830185903956b5925796cfa68c5b61fa3c3b3f0f2cb.ttf
I/flutter (18496):
```

**Comment by guidezpl** [comment]
Did you follow the troubleshooting steps printed?
