### ISSUE TITLE
AdaptiveNavigationScaffold Collapsed Bar Removes Items

### ISSUE THREAD

**Issue by WH-Creations** [material-foundation/flutter-packages#391]
### Package

adaptive_navigation

### Existing issue?

- [X] I checked the [existing issues](https://github.com/material-foundation/flutter-packages/issues)

## Expected vs actual result:
If I have a navigation scaffold with 10 items in it when expanded, I expect there still to be 10 items when I collapse the side bar.

What actually happens is the bottom 3 items are removed and I only have 7 items to select from in the collapsed side bar.

## Steps to reproduce:
1. Create a simple project and add an AdaptiveNavigationScaffold with 10 items.
2. Resize the window until the side bar collapses to just show icons.
3. You'll see it only shows up to 7 items in the side bar.

**Comment by guidezpl** [comment]
Closing this issue due to discontinuation of the adaptive packages.
