### ISSUE TITLE
Flutter 3.7.12 with fails with AGP version 8.0+

### ISSUE THREAD

**Issue by guidezpl** [material-foundation/flutter-packages#392]
### Package

dynamic_color

### Existing issue?

- [X] I checked the [existing issues](https://github.com/material-foundation/flutter-packages/issues)

## Expected vs actual result:
Crash

## Steps to reproduce:
1. Create a new Flutter Application (empty)
2. Use Android Studio's "AGP Upgrade Assistant" to upgrade to Gradle 8
3. `flutter pub add dynamic_color` (or any other package that has a native component like `mobile_scanner`)
4. Gradle sync

We should also ensure the example apps are runnable. 

See https://github.com/flutter/flutter/issues/125181 for `flutter/packages` issue, in particular https://github.com/flutter/flutter/issues/125181#issuecomment-1516647803.

**Comment by guidezpl** [comment]
Fixed by https://github.com/material-foundation/flutter-packages/commit/0f70b505eeb2e477347f081002bc6d7ed2b884d4

**Comment by guidezpl** [comment]
It was published 4 days ago

**Comment by FauconSpartiate** [comment]
Guess I overlooked something then, thank you 👍
