### ISSUE TITLE
The Spaces are too spaced.

### ISSUE THREAD

**Issue by licheng1013** [material-foundation/flutter-packages#393]
### Package

google_fonts

### Existing issue?

- [X] I checked the [existing issues](https://github.com/material-foundation/flutter-packages/issues)

## Expected vs actual result:

![image](https://user-images.githubusercontent.com/46236080/233935732-3a3e5164-24ba-4260-a8a0-91b06bf5cc5b.png)

## Steps to reproduce:
- Key sample code.

```dart
TextStyle getTextTheme() {
  return GoogleFonts.notoColorEmoji();
}
```

**Comment by guidezpl** [comment]
There isn't enough information to reproduce... Can you please provide a full code sample?

**Comment by licheng1013** [comment]
> There isn't enough information to reproduce... Can you please provide a full code sample?

![image](https://user-images.githubusercontent.com/46236080/234023014-f87cf3a5-84cc-4a5c-aeed-5bf90f40c5ff.png)

``` dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:google_fonts/google_fonts.dart';

void main() {
  GoogleFonts.config.allowRuntimeFetching = false;
  runApp(GetMaterialApp(
    theme: ThemeData(
      // 开启m3
      useMaterial3: true,
      // 设置主题色
      colorSchemeSeed: Colors.blue,
    ),
    home: const TextTest(),
    // 去除右上角debug标签
    debugShowCheckedModeBanner: false,
  ));
}

class TextTest extends StatelessWidget{
  const TextTest({super.key});
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Text(
        "Hello World",
        style: GoogleFonts.notoColorEmoji(),
      ),
    );
  }
}
```

**Comment by guidezpl** [comment]
I see thank you, it seems this font is [meant for emojis](https://fonts.google.com/noto/specimen/Noto+Color+Emoji?preview.text=test%20test%20&preview.text_type=custom), and only supports text incidentally on Flutter. I suggest only using this font for emojis, and using another supported font for text.

**Comment by licheng1013** [comment]
Thank you.
