### ISSUE TITLE
[adaptive_breakpoints] Support for Material 3 Window sizes

### ISSUE THREAD

**Issue by icnahom** [material-foundation/flutter-packages#402]
### Package

adaptive_breakpoints

### Description

Are there plans to migrate to the new material 3 breakpoints?
https://m3.material.io/foundations/layout/applying-layout/window-size-classes

**Comment by yanshouwang** [comment]
Any plans?

**Comment by icnahom** [comment]
Since material 3 is a different spec, this package may need a full rewrite or we could have a different package called `adaptive_window_size`.

More resource:
https://developer.android.com/guide/topics/large-screens/support-different-screen-sizes#window_size_classes

https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/material3/material3-window-size-class/src/commonMain/kotlin/androidx/compose/material3/windowsizeclass/WindowSizeClass.kt

**Comment by icnahom** [comment]
@guidezpl I could create a PR, but which direction go with?

**Comment by guidezpl** [comment]
https://pub.dev/packages/flutter_adaptive_scaffold is somewhat better supported. 

We could have just the sizes here though, so that M2 users have an upgrade path to M3.

Either way, I can only provide advice as I'm working on non-Flutter things

**Comment by guidezpl** [comment]
Closing this issue due to discontinuation of the adaptive packages.
