### ISSUE TITLE
iOS build conflict with google_fonts due to asset_manifest import on Flutter 3.10.1

### ISSUE THREAD

**Issue by diegomontejano** [material-foundation/flutter-packages#403]
### Package

google_fonts

### Existing issue?

- [X] I checked the [existing issues](https://github.com/material-foundation/flutter-packages/issues)

## Issue: 
![Screenshot 2023-05-18 at 11 30 55](https://github.com/material-foundation/flutter-packages/assets/115236196/4f156b42-ea03-4b46-915a-95113b28bc18)

## Versions: 
![Screenshot 2023-05-18 at 11 45 48](https://github.com/material-foundation/flutter-packages/assets/115236196/67c937b9-fbcf-47dd-b98a-99f24bbeea2f)

### Relevant log output

```shell
Launching lib/main.dart on iPhone 13 in debug mode...
main.dart:1
Xcode build done.                                           10.8s
Failed to build iOS app
Error (Xcode): ../../../../../.pub-cache/hosted/pub.dev/google_fonts-2.2.0/lib/src/google_fonts_base.dart:14:1: Error: 'AssetManifest' is imported from both 'package:flutter/src/services/asset_manifest.dart' and 'package:google_fonts/src/asset_manifest.dart'.
google_fonts_base.dart:14
Could not build the application for the simulator.
Error launching application on iPhone 13.
Exited
```

**Comment by guidezpl** [comment]
Version `4.0.1` addresses this: :) closing
