### ISSUE TITLE
Update   new   http    1.0.0 

### ISSUE THREAD

**Issue by samithe7** [material-foundation/flutter-packages#404]
### Package

google_fonts

### Description

Because google_fonts 4.0.4 depends on http ^0.13.0 and no versions of google_fonts match >4.0.4 <5.0.0, google_fonts ^4.0.4 requires http ^0.13.0.
So, because corenews depends on both google_fonts ^4.0.4 and http ^1.0.0, version solving failed.

**Comment by thorizer** [comment]
i had the same output just now.

**Comment by guidezpl** [comment]
I've published `4.0.5`. If anyone needs time to update their app to Dart 3 (an `http` 1.0.0 restriction), you can pin to the previous version with `google_fonts: 4.0.4`.
