### ISSUE TITLE
[dynamic_color] Release build prints "Accent color detected." in console

### ISSUE THREAD

**Issue by PeterNjeim** [material-foundation/flutter-packages#448]
### Package

dynamic_color

### Existing issue?

- [X] I checked the [existing issues](https://github.com/material-foundation/flutter-packages/issues)

## Expected vs actual result:
Expectation: nothing printed to console
Actuality: `flutter: dynamic_color: Accent color detected.` printed to console

## Steps to reproduce:
1. Use `DynamicColorBuilder`
2. Build Linux release application
3. Run binary

## Notes
From this line in the code: https://github.com/material-foundation/flutter-packages/blob/76e9f094d2465eaed327135296777493c3984f59/packages/dynamic_color/lib/src/dynamic_color_builder.dart#L84 While it may seem like it does, `debugPrint` doesn't mean "print only in debug mode", it means it "throttles the output to a level that avoids being dropped by Android’s kernel." Best practice is not to include prints in production in code, so I recommend deleting the lines that use `debugPrint` in the `dynamic_color` package, and possibly all non-error prints in the repository (maybe change this line: https://github.com/material-foundation/flutter-packages/blob/76e9f094d2465eaed327135296777493c3984f59/analysis_options.yaml#L10 to `true` to make it easier).

**Comment by guidezpl** [comment]
Yeah, you would think `debugPrint` only prints in debug mode. Easy fix
