### ISSUE TITLE
miss font Noto Sans SC

### ISSUE THREAD

**Issue by magixyu** [material-foundation/flutter-packages#451]
### Package

google_fonts

### Existing issue?

- [X] I checked the [existing issues](https://github.com/material-foundation/flutter-packages/issues)

## Expected vs actual result:
Noto Sans SC in the package.
https://fonts.google.com/noto/specimen/Noto+Sans+SC

## Steps to reproduce:
1.
1.
1.

### Relevant log output

```shell
NA-
```

**Comment by guidezpl** [comment]
Duplicate of https://github.com/material-foundation/flutter-packages/issues/126
