### ISSUE TITLE
Disclude example folder from pacakges

### ISSUE THREAD

**Issue by guyluz11** [material-foundation/flutter-packages#469]
### Package

All packages

### Description

Downloading the package from pub.dev contains the example folder.

Because of that searching code current project files includes example results

![image](https://github.com/material-foundation/flutter-packages/assets/9304740/eda778fb-7da5-4185-bed5-34129f29e184)

As written here https://github.com/dart-lang/pub-dev/issues/5862 you need to manually add `example` folder to `.pubignore`

**Comment by guidezpl** [comment]
Since this is an issue affecting all packages with examples, I'll let the pub folks come up with a global solution.

**Comment by guyluz11** [comment]
They close the issue with the massage that the packages should implement it.

Please keep this issue open until they decided to go forward and solve it.

**Comment by guidezpl** [comment]
There are thousands of packages on pub, the churn is just not worth it for developers. A single solution is preferable

**Comment by guyluz11** [comment]
I totally agree that a single solution is needed.
Can you share your opinion with them?, post it in the mentioned link so that they will hear more options

**Comment by guidezpl** [comment]
Sure.
