### ISSUE TITLE
support https://fonts.google.com/noto/specimen/Noto+Serif+SC

### ISSUE THREAD

**Issue by zhujiageng** [material-foundation/flutter-packages#479]
### Package

google_fonts

### Existing issue?

- [X] I checked the [existing issues](https://github.com/material-foundation/flutter-packages/issues)

### What happened?

currently only support support https://fonts.google.com/noto/specimen/Noto+Sans+SC, please alse add support for https://fonts.google.com/noto/specimen/Noto+Serif+SC

**Comment by guidezpl** [comment]
duplicate of https://github.com/material-foundation/flutter-packages/issues/126
