### ISSUE TITLE
version solving failed

### ISSUE THREAD

**Issue by MominRaza** [material-foundation/flutter-packages#480]
### Package

dynamic_color

### Existing issue?

- [X] I checked the [existing issues](https://github.com/material-foundation/flutter-packages/issues)

### What happened?

flutter_test using `material_color_utilities` v0.8.0, but `dynamic_color` is limiting to v0.2.0 to v0.5.0

### Relevant log output

``` console
Resolving dependencies...
Note: material_color_utilities is pinned to version 0.8.0 by flutter_test from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.

Because every version of flutter_test from sdk depends on material_color_utilities 0.8.0 and dynamic_color >=1.6.5 depends on material_color_utilities >=0.2.0 <=0.5.0, flutter_test from sdk is incompatible with dynamic_color >=1.6.5.
So, because apnapan depends on both dynamic_color ^1.6.7 and flutter_test from sdk, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on dynamic_color: flutter pub add dynamic_color:^0.0.1
exit code 1
```

### Related issue

https://github.com/material-foundation/material-color-utilities/issues/119

**Comment by MasiaVittorio** [comment]
Yeah, can't use this package while using Flutter's master channel because of this (and can't work on stable because I depend on some fixes that are only on master right now rip)

**Comment by guidezpl** [comment]
Indeed (https://github.com/flutter/flutter/pull/132445), let me publish a new version
