### ISSUE TITLE
[dynamic_color] not support windows 8.1 

### ISSUE THREAD

**Issue by 110** [material-foundation/flutter-packages#523]
### Package

dynamic_color

### Existing issue?

- [X] I checked the [existing issues](https://github.com/material-foundation/flutter-packages/issues)

### What happened?

 
![截屏2023-12-25 22 46 16](https://github.com/material-foundation/flutter-packages/assets/1701009/d5f043b2-b30c-4d69-ab60-5069f73a2763)

If Not support windows 8.1 , It's can block or hidden  or what want ?

**Comment by guidezpl** [comment]
Hi, Flutter is dropping support for Windows 7 and 8, so I have to regretably close this issue. https://medium.com/flutter/whats-new-in-flutter-3-19-58b1aae242d2#:~:text=Dropping%20Windows%207%20and%208%20support
