### ISSUE TITLE
Google Font Load Error

### ISSUE THREAD

**Issue by Iamgauravkanani** [material-foundation/flutter-packages#572]
### Package

google_fonts

### Existing issue?

- [X] I checked the [existing issues](https://github.com/material-foundation/flutter-packages/issues)

## Steps to reproduce:
1.
1.
1.
/C:/Users/smrty/AppData/Local/Pub/Cache/hosted/pub.dev/google_fonts-2.1.1/lib/src/google_fonts_base.dart:14:1: Error: 'AssetManifest' is imported from both 'package:flutter/src/services/asset_manifest.dart' and 'package:google_fonts/src/asset_manifest.dart'.
import 'asset_manifest.dart';
^^^^^^^^^^^^^
/C:/Users/smrty/AppData/Local/Pub/Cache/hosted/pub.dev/google_fonts-2.1.1/lib/src/google_fonts_base.dart:32:31: Error: 'AssetManifest' is imported from both 'package:flutter/src/services/asset_manifest.dart' and 'package:google_fonts/src/asset_manifest.dart'.
AssetManifest assetManifest = AssetManifest();

### Relevant log output

```shell
/C:/Users/smrty/AppData/Local/Pub/Cache/hosted/pub.dev/google_fonts-2.1.1/lib/src/google_fonts_base.dart:14:1: Error: 'AssetManifest' is imported from both 'package:flutter/src/services/asset_manifest.dart' and 'package:google_fonts/src/asset_manifest.dart'.
import 'asset_manifest.dart';
^^^^^^^^^^^^^
/C:/Users/smrty/AppData/Local/Pub/Cache/hosted/pub.dev/google_fonts-2.1.1/lib/src/google_fonts_base.dart:32:31: Error: 'AssetManifest' is imported from both 'package:flutter/src/services/asset_manifest.dart' and 'package:google_fonts/src/asset_manifest.dart'.
AssetManifest assetManifest = AssetManifest();
```

**Comment by guidezpl** [comment]
Hi, you're using a really old version of `google_fonts` (it's currently `6.2.1`), please upgrade.
