### ISSUE TITLE
Error: Type 'FontFeature' not found.

### ISSUE THREAD

**Issue by mUmarBaloch** [material-foundation/flutter-packages#581]
### Package

All packages

### Existing issue?

- [X] I checked the [existing issues](https://github.com/material-foundation/flutter-packages/issues)

### What happened?

../../../AppData/Local/Pub/Cache/hosted/pub.dev/google_fonts-6.2.0/lib/src/google_fonts_base.dart:69:8: Error: Type 'FontFeature' not found.
  List<FontFeature>? fontFeatures,
       ^^^^^^^^^^^

**Comment by serdarpolat** [comment]
for now downgrade to 6.1.0. also remove caret (^)
`google_fonts: 6.1.0`
