### ISSUE TITLE
A problem occurred configuring project ':dynamic_color'.

### ISSUE THREAD

**Issue by Epic-R-R** [material-foundation/flutter-packages#583]
### Package

dynamic_color

### Existing issue?

- [X] I checked the [existing issues](https://github.com/material-foundation/flutter-packages/issues)

## Expected vs actual result:
Run project for test with dynamic_color but when build project this happened
` not resolve all files for configuration ':dynamic_color:classpath'.
   > Could not find app.android.tools.build:gradle:7.4.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/app/android/tools/build/gradle/7.4.2/gradle-7.4.2.pom
       - https://repo.maven.apache.org/maven2/app/android/tools/build/gradle/7.4.2/gradle-7.4.2.pom
     Required by:
         project :dynamic_color
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':dynamic_color' of type org.gradle.api.Project.
   > Could not get unknown property 'android' for project ':dynamic_color' of type org.gradle.api.Project.

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
`

## Steps to reproduce:
1. Create flutter project
`flutter create testProject`
2. Add `dynamic_color` package to project
`flutter pub add dynamic_color`
3. Run project
`flutter run`

**Comment by guidezpl** [comment]
Sorry, but I'm unable to reproduce this error. If this is still occurring with a newly created project with the latest stable version of Flutter, please reopen and provide as much information as useful for identifying the root cause.
