### ISSUE TITLE
``surfaceContainer`` is  a complete white color, when it shouldn't be

### ISSUE THREAD

**Issue by JGeek00** [material-foundation/flutter-packages#595]
### Package

dynamic_color

### Existing issue?

- [X] I checked the [existing issues](https://github.com/material-foundation/flutter-packages/issues)

## Expected vs actual result:
I think this started happening with Flutter v3.22, because previously I didn't had to define the ``cardTheme``, ``popupMenuTheme``, and ``navigationBarTheme`` to match the colors of the Material 3 specification, but currently if I don't define that parameters with the correct background color, the background color of that components is rendered white.

<img width="388" alt="image" src="https://github.com/material-foundation/flutter-packages/assets/47545344/fc758c54-f583-4dcc-8e55-b5d1eadcae35">
<img width="218" alt="image" src="https://github.com/material-foundation/flutter-packages/assets/47545344/2699515e-7c3d-4a59-9180-886ba1c00ad0">
<img width="390" alt="image" src="https://github.com/material-foundation/flutter-packages/assets/47545344/ad6c777e-216f-4c7f-acfe-e9f6ada9ba20">

If I don't use the dynamic color scheme and instead I use a normal color, it works fine.
<img width="387" alt="image" src="https://github.com/material-foundation/flutter-packages/assets/47545344/d7834a7c-4c44-4abf-b1fe-add4e114ecb7">
<img width="214" alt="image" src="https://github.com/material-foundation/flutter-packages/assets/47545344/d1fb2935-7f18-470a-a375-e147f939e57a">
<img width="389" alt="image" src="https://github.com/material-foundation/flutter-packages/assets/47545344/9520460c-4bd4-4443-84a9-3c08972f9063">

This happens because now the ``surfaceContainer`` color is completely white (I mean rgb(0, 0, 0)), and according to the Material 3 specification, that color is the one that has to be used for the container background.

https://m3.material.io/components/cards/specs
<img width="981" alt="image" src="https://github.com/material-foundation/flutter-packages/assets/47545344/092f5970-f43c-4f1a-be25-a965aa224859">

https://m3.material.io/components/menus/specs
<img width="975" alt="image" src="https://github.com/material-foundation/flutter-packages/assets/47545344/c5fd4f14-3567-4b3a-9a50-57030e64081a">

https://m3.material.io/components/navigation-bar/specs
<img width="973" alt="image" src="https://github.com/material-foundation/flutter-packages/assets/47545344/3a2f608b-c9b1-46ad-a0ac-67b9c32202a0">

If I define that colors on the teme with ``surfaceTint`` instead of with ``surfaceContainer``, the correct color is applied.
```dart
  cardTheme: CardTheme(
    surfaceTintColor: dynamicColorScheme?.surfaceTint
  ),
  popupMenuTheme: PopupMenuThemeData(
    surfaceTintColor: dynamicColorScheme?.surfaceTint
  ),
  navigationBarTheme: NavigationBarThemeData(
    surfaceTintColor: dynamicColorScheme?.surfaceTint
  )
```

**Comment by Zensonaton** [comment]
I have no idea who from the Flutter team thought that making this breaking change is a good idea.

Why haven't they passed `dynamicSchemeVariant: DynamicSchemeVariant.fidelity` by default? Ew.

**Comment by guidezpl** [comment]
Closing as dupe (e.g. #591)
